// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using niverTchelo.Data;

namespace niverTchelo.Migrations
{
    [DbContext(typeof(niverTcheloContext))]
    [Migration("20191027062606_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("niverTchelo.Models.Convidados", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<string>("Mensagem");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Presenca");

                    b.HasKey("Id");

                    b.ToTable("Convidados");
                });
#pragma warning restore 612, 618
        }
    }
}
